name: vocab_master
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.1.1
  flutter_tts: ^3.8.3
  fl_chart: ^0.65.0
  intl: ^0.19.0
  file_picker: ^10.3.8
  shared_preferences: ^2.2.2
  http: ^1.2.2
  sqflite_common_ffi_web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
